### ISSUE TITLE
Would you mind including an inference script for trained up_down and show_and_tell models?

### ISSUE THREAD

**Issue by rushingcreek** [brandontrabucco/conceptual_captions#1]

**Comment by brandontrabucco** [comment]
Hi @rushingcreek, thanks for your interest in my code. Unfortunately, I do not have the time at the moment to work on making an inference script, but if you would like a pretrained Bottom Up and Top Down Attention model (though not trained on the conceptual captions), you can use pythia: https://github.com/facebookresearch/pythia
